#!/bin/sh
# articlemenu

# Copyright (c) 2017–2026 Denis Kasak
# Distributed under the ISC licence.

# requires rofi xdg-open

ARTICLE_STORE=~/docs/articles
PRESENTATION_STORE=~/docs/presentations
MANUAL_STORE=~/docs/manuals
VULNERABILITY_REPORT_STORE=~/docs/vulnerability-reports

get_articles() {
    find "$ARTICLE_STORE" "$MANUAL_STORE" "$VULNERABILITY_REPORT_STORE" "$PRESENTATION_STORE" \
        \( -type f -or -type l \) -and -not -path '*/.*' -printf '%P\0'
}

launch_reader() {
    read -r article
    xdg-open "$article"
}

yank_path() {
    xsel -ib
}

resolve_article() {
    read -r filename

    if [ -r "$ARTICLE_STORE/$filename" ]; then
        printf '%s' "$ARTICLE_STORE/$filename"
    elif [ -r "$MANUAL_STORE/$filename" ]; then
        printf '%s' "$MANUAL_STORE/$filename"
    elif [ -r "$VULNERABILITY_REPORT_STORE/$filename" ]; then
        printf '%s' "$VULNERABILITY_REPORT_STORE/$filename"
    fi
}

menu() {
    rofi -kb-custom-1 'Alt+y' -dmenu -i -lines 20 -p "articlemenu (alt+y to yank path)"
}

choice=$(get_articles | sort -z | sed -e 's/\x0/\n/g' | menu)
ret=$?

if [ -z "$choice" ]; then
    exit 1
fi

filename="$(printf '%s' "$choice" | resolve_article)"

if [ "$ret" -eq 0 ]; then 
    printf '%s' "$filename" | launch_reader 
elif [ "$ret" -ge 10 ] && [ "$ret" -le 28 ]; then
    printf '%s' "$filename" | yank_path
fi
