#!/bin/sh --
# articlemenu

# Copyright (c) 2017 Denis Kasak
# Distributed under the ISC licence.

# requires rofi xdg-open

ARTICLE_STORE=~/docs/articles
PRESENTATION_STORE=~/docs/presentations
MANUAL_STORE=~/docs/manuals
VULNERABILITY_REPORT_STORE=~/docs/vulnerability-reports

getarticles() {
    find "$ARTICLE_STORE" "$MANUAL_STORE" "$VULNERABILITY_REPORT_STORE" "$PRESENTATION_STORE" \
        \( -type f -or -type l \) -and -not -path '*/.*' -printf '%P\0'
}

launchreader() {
    # shellcheck disable=SC2039
    read -r article

    if [ -r "$ARTICLE_STORE/$article" ]; then
        xdg-open "$ARTICLE_STORE/$article"
    elif [ -r "$MANUAL_STORE/$article" ]; then
        xdg-open "$MANUAL_STORE/$article"
    elif [ -r "$VULNERABILITY_REPORT_STORE/$article" ]; then
        xdg-open "$VULNERABILITY_REPORT_STORE/$article"
    fi
}

menu() {
    rofi -dmenu -i -lines 20 -p "articlemenu"
}

choice=$(getarticles | sort -z | sed -e 's/\x0/\n/g' | menu)

if [ -z "$choice" ]; then
    exit 1
fi

printf "%s" "$choice" | launchreader
