#!/bin/sh --
# bookmenu - create a menu using calibredb

# Copyright (c) 2017–2025 Damir Jelić, Denis Kasak.
# Distributed under the ISC licence.

# requires calibredb jq rofi xdg-open

get_books() {
    calibredb list --fields=title,authors,formats --for-machine
}

to_choices() {
    jq -r '.[] | "\(.title) – \(.authors)\t\(.id)"'
}

available_formats_of() {
    jq -r --argjson choice "$1" '.[] | select(.id == $choice) | .formats'
}

# Pick a book file, preferring PDF over other formats
pick_file() {
    jq -r '(map(select(endswith("pdf"))) | .[]) // .[0]'
}

launch_reader() {
    # shellcheck disable=SC2039
    local bookpath
    read -r bookpath
    xdg-open "$bookpath"
}

menu() {
    rofi -dmenu -display-columns 1 -display-column-separator '\t' -i -lines 20 -p "bookmenu" | awk -F'\t' '{print $2}'
}

books=$(get_books) &&
    choice=$(printf "%s" "$books" | to_choices | sort | menu) &&
    echo "$choice" &&
    printf "%s" "$books" | available_formats_of "$choice" | pick_file | launch_reader
