#!/bin/sh
# recent-documents - open a recently opened document (with zathura) using a rofi menu

# Copyright (c) 2017–2026 Denis Kasak
# Distributed under the ISC licence.

# requires rofi sqlite3 zathura

if [ -z "$XDG_DATA_HOME" ]; then
    XDG_DATA_HOME="$HOME/.local/share"
fi

recent_documents() {
    # grep -o "\[.*\]" "$XDG_DATA_HOME/zathura/history" | tr -d "[]" | tac
    sqlite3 "$XDG_DATA_HOME/zathura/bookmarks.sqlite" "SELECT file FROM fileinfo WHERE file NOT LIKE '/IMPORTED/%' ORDER BY time DESC"
}

filter_existing() {
    while read -r filename; do
        [ -e "$filename" ] && printf "%s\n" "$filename"
    done
}

menu() {
    rofi -dmenu -p "recent documents"

    # zenity-based alternative menu
    #
    # zenity --list --multiple --title="Previously opened documents" \
    #        --column="Document" --width=800 --height=500 --separator="\n" \
}

choice="$(recent_documents | filter_existing | menu)"

if [ -z "$choice" ]; then
    exit 1
fi

xdg-open "$choice"
