#!/bin/sh

# Remind of due or overdue TaskWarrior tasks.
#
# Best used with anacron or similar.

export TASKRC=~/.config/taskrc
export DISPLAY=:1

task +TODAY or +TOMORROW or +OVERDUE export \
    | jq '.[] | .description' 2>/dev/null           \
    | xargs --no-run-if-empty -n1 notify-send \
            -a remind \
            -t 0 \
            -u low
